-- MySQL Script generated by MySQL Workbench
-- Fri May 23 21:56:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema touchepasauklaxon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema touchepasauklaxon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `touchepasauklaxon` DEFAULT CHARACTER SET utf8 ;
USE `touchepasauklaxon` ;

-- -----------------------------------------------------
-- Table `touchepasauklaxon`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touchepasauklaxon`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `tel` VARCHAR(15) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touchepasauklaxon`.`agences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touchepasauklaxon`.`agences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ville` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `ville_UNIQUE` (`ville` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `touchepasauklaxon`.`trajets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `touchepasauklaxon`.`trajets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auteur` INT NOT NULL,
  `date_depart` DATETIME NOT NULL,
  `date_destination` DATETIME NOT NULL,
  `places` INT NOT NULL,
  `agence_depart` INT NOT NULL,
  `agence_destination` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_idx` (`auteur` ASC) VISIBLE,
  INDEX `fk_agence_depart_idx` (`agence_depart` ASC) VISIBLE,
  INDEX `fk_agence_destination_idx` (`agence_destination` ASC) INVISIBLE,
  CONSTRAINT `fk_user`
    FOREIGN KEY (`auteur`)
    REFERENCES `touchepasauklaxon`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agence_depart`
    FOREIGN KEY (`agence_depart`)
    REFERENCES `touchepasauklaxon`.`agences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agence_destination`
    FOREIGN KEY (`agence_destination`)
    REFERENCES `touchepasauklaxon`.`agences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Contrainte pour que le nombre de places soit strictement positif
ALTER TABLE `touchepasauklaxon`.`trajets`
ADD CONSTRAINT `chk_places_positive`
CHECK (`places` > 0);

-- Contrainte pour que la date de destination soit postérieure à la date de départ
ALTER TABLE `touchepasauklaxon`.`trajets`
ADD CONSTRAINT `chk_dates_valides`
CHECK (`date_destination` > `date_depart`);

CREATE USER 'admin' IDENTIFIED BY 'P@ssw0rd';

GRANT ALL ON `touchepasauklaxon`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
